### ISSUE TITLE
question about the code in calculating reward

### ISSUE THREAD

**Issue by andyclsr** [YangRui2015/RiC#11]
Hi, I have a question about the code about calculating the reward below:
https://github.com/YangRui2015/RiC/blob/f8fa613d1dbe28c59b83801666558f4282925dd7/ppo/utils.py#L246

Why the reward is truncated to one decimal fraction? It is of purpose? I also see many places set like this. Will the reward lack of accuracy lead to a worse performance of ppo?

Look forward to your reply!

**Comment by YangRui2015** [comment]
Hi, this is to be compatible with RiC, where a too long reward string can be harmful because we need input the rewards into prompts. PPO may not need such truncation. But in my experience, it does not significantly affect the results. Feel free to give it a try.

**Comment by andyclsr** [comment]
Oh, I see. Thanks for your prompt reply again!
