### ISSUE TITLE
Code related to Stable Diffusion

### ISSUE THREAD

**Issue by EvaFlower** [YangRui2015/RiC#12]
Hi, interesting work. 

I wonder if you will release the code of the text-to-image task in the near future? 

I am interested in reproducing the results on that part. How do you incorporate the condition of rewards into Stable Diffusion?

Best,

**Comment by YangRui2015** [comment]
Thank you for your interest in our work. The implementation details are in Appendix C.1.  We also have updated the code in the ric_txt2img directory.

**Comment by EvaFlower** [comment]
Thanks for your update. I will look into them.

**Comment by EvaFlower** [comment]
Hi,

I have looked into the code. May you provide the file indicated in the train.sh ``export TRAIN_JSON="/mnt/aigc_cq/private/amandaaluo/dataset/multi_obj/multi_obj_with_clip_base.json" ``.

Also, I wonder if you could release your trained model checkpoints for ease of evaluation. 

Best,

**Comment by YangRui2015** [comment]
@amandaluof will have a look into this soon.

**Comment by amandaluof** [comment]
> Hi,
> 
> I have looked into the code. May you provide the file indicated in the train.sh `export TRAIN_JSON="/mnt/aigc_cq/private/amandaaluo/dataset/multi_obj/multi_obj_with_clip_base.json" `.
> 
> Also, I wonder if you could release your trained model checkpoints for ease of evaluation.
> 
> Best,

Thanks for your attention. We have released our checkpoint and give an instruction in README.md.
