### ISSUE TITLE
A question about Table 1 in the paper

### ISSUE THREAD

**Issue by CurryxIaoHu** [YangRui2015/RiC#6]
Hello! Thanks for your interesting work. But I have a question, why the authors claim that MODPO is capable of Inference adaptation(in Table 1)? It seems like that MODPO doesn't allow users to modify their own preferences and the model's weight is also fixed. That confuses me a lot.

**Comment by YangRui2015** [comment]
Sorry for the confusion. You are correct; MODPO is not adaptive. The original writing in MODPO was a bit unclear, and I realized this when I ran its code. However, I forgot to update the camera-ready version. I will correct this in the arXiv version.

**Comment by YangRui2015** [comment]
Close as fixed.
