### ISSUE TITLE
Questions on Preparing datasets

### ISSUE THREAD

**Issue by andyclsr** [YangRui2015/RiC#7]
Hi, thanks for your wonderful work and for sharing the code!
I ran the script of "preparing datasets"
```shell
CUDA_VISIBLE_DEVICES=0,1,2,3 accelerate launch prepare_dataset_with_rewards.py --reward_names 'summary,faithful' --exp_type 'summary' --save_directory './datasets/summary_pref1faithful.hf'
``` 
and it seems like there is a warning "You passed along num_labels=3 with an incompatible id to label map: {'0': 'HALLUCINATED', '1': 'FAITHFUL'}. The number of labels wil be overwritten to 2.".
I check the code but failed to find where to trigger this . And about the 'num_labels', I guess it is where the variable is set. https://github.com/YangRui2015/RiC/blob/f8fa613d1dbe28c59b83801666558f4282925dd7/ric/utils.py#L395
But it is not 3 but 2. Or I found the wrong place.
Do you know what happened and could I just ignore it ?
<img width="1791" alt="image" src="https://github.com/user-attachments/assets/012257bc-6d95-4092-b62d-5e89936e5a3f">

**Comment by YangRui2015** [comment]
Thank you for your interest in our work. I encountered this warning as well, but I found that it didn't have any impact. You can just ignore it.

**Comment by andyclsr** [comment]
Thanks for the rapid reply!
