### ISSUE TITLE
A question about the code of sft

### ISSUE THREAD

**Issue by andyclsr** [YangRui2015/RiC#9]
Hi, I have a question about the code of sft.
As the code belows are processing the entry "query". 
https://github.com/YangRui2015/RiC/blob/f8fa613d1dbe28c59b83801666558f4282925dd7/sft/utils.py#L138-L139
It calls encode function and as in usual the function will add special tokens into the encoding. However, in the case of llama, it fails to add eos only bos token which makes the model after sft failed to predict eos token. This could be verified by a simple experiment or here are some discussions: https://github.com/huggingface/transformers/issues/22794.

I tested the generation of llama before and after sft, belows are the results:
before sft
<img width="2049" alt="企业微信截图_27683f43-b9a4-4c16-9bb1-8988a638df2e" src="https://github.com/user-attachments/assets/23e5bf60-5f63-43ba-8c29-9f6a10845735">
after sft
<img width="2164" alt="企业微信截图_74da43b5-7f90-43cb-be32-ef7d78d807cd" src="https://github.com/user-attachments/assets/fac128c4-9fb9-47fc-a60c-aa5258a1856a">

Did the llama you sft do the same thing like this? Is this ignorance or my misunderstanding? Hope for your reply!

**Comment by andyclsr** [comment]
There is also another tiny question: is after sft merging lora into a unified model necessary for ppo? Can I skip the merging step?

**Comment by YangRui2015** [comment]
Thanks for your question. I encountered the same problem but haven't been able to fix it. As you mentioned, this discussion might offer a solution: https://github.com/huggingface/transformers/issues/22794#issuecomment-1598977285.

In my code, merging LoRA into the model is necessary for PPO. I’ve tested it before and encountered unexpected errors when it wasn't merged.

**Comment by andyclsr** [comment]
I see. Thanks for your rapid reply! : )
